OpenRouter_GLM-4.5-Air_131k=z-ai/glm-4.5-air\:free
OpenRouter_Llama_3.3_70B=meta-llama/llama-3.3-70b-instruct\:free
OpenRouter_TNG/DeepSeek_R1T2_Chimera_671b-163k=tngtech/deepseek-r1t2-chimera\:free
OpenRouter_TNG/DeepSeek_R1T_Chimera_671b-163k=tngtech/tng-r1t-chimera\:free
OpenRouter_Nous_Hermes_3_405b-Instruct-131k=nousresearch/hermes-3-llama-3.1-405b\:free
OpenRouter_Mistral_small_3.1_24b-instruct-128k=mistralai/mistral-small-3.1-24b-instruct\:free
OpenRouter_GPT_OSS_120b=openai/gpt-oss-120b\:free
OpenRouter_GPT_OSS_20b=openai/gpt-oss-20b\:free
#OpenRouter_Qwen_Qwen3_4b=qwen/qwen3-4b\:free
OpenRouter_Qwen_Qwen3_Coder_480b-a35b-262k=qwen/qwen3-coder\:free
OpenRouter_Qwen_Qwen3-next_80b-a3b-instruct-262k=qwen/qwen3-next-80b-a3b-instruct\:free
OpenRouter_Qwen_Qwen3_235b-a22b-Thinking-2507-131k=qwen/qwen3-235b-a22b-thinking-2507
OpenRouter_StepFun_Step_3.5_Flash_196b-a11b-256k=stepfun/step-3.5-flash\:free
OpenRouter_Arcee_AI_Trinity_Large_Preview_400b-a13b-131k=arcee-ai/trinity-large-preview\:free
OpenRouter_NVIDIA_Nemotron_3_Nano_30b-a3b-256k=nvidia/nemotron-3-nano-30b-a3b\:free
Groq_GPT_OSS_120b=openai/gpt-oss-120b
Groq_GPT_OSS_20=openai/gpt-oss-20b
Groq_kimi_k2_instruct_0905=moonshotai/kimi-k2-instruct-0905
Groq_qwen3_32b=qwen/qwen3-32b
Groq_Llama_3.3_70b_versatile=llama-3.3-70b-versatile
Groq_Llama_3.1_8b_instant=llama-3.1-8b-instant
Groq_Llama_4_17b_128e_instruct=meta-llama/llama-4-maverick-17b-128e-instruct
Groq_Llama_4_17b_16e_instruct=meta-llama/llama-4-scout-17b-16e-instruct
