OpenRouter_GLM-4.5-Air=z-ai/glm-4.5-air\:free
OpenRouter_Llama_3.3_70B=meta-llama/llama-3.3-70b-instruct\:free
OpenRouter_DeepSeek_R1=tngtech/deepseek-r1t2-chimera\:free
OpenRouter_Hermes_3_405b=nousresearch/hermes-3-llama-3.1-405b\:free
OpenRouter_Mistral_small_3.1_24b_instruct=mistralai/mistral-small-3.1-24b-instruct\:free
OpenRouter_GPT_OSS_120b=openai/gpt-oss-120b\:free
OpenRouter_GPT_OSS_20b=openai/gpt-oss-20b\:free
OpenRouter_Qwen_3_coder=qwen/qwen3-coder\:free
OpenRouter_Qwen_3_4b=qwen/qwen3-4b\:free
Groq_GPT_OSS_120b=openai/gpt-oss-120b
Groq_GPT_OSS_20=openai/gpt-oss-20b
Groq_kimi_k2_instruct_0905=moonshotai/kimi-k2-instruct-0905
Groq_qwen3_32b=qwen/qwen3-32b
Groq_Llama_3.3_70b_versatile=llama-3.3-70b-versatile
Groq_Llama_3.1_8b_instant=llama-3.1-8b-instant
Groq_Llama_4_17b_128e_instruct=meta-llama/llama-4-maverick-17b-128e-instruct
Groq_Llama_4_17b_16e_instruct=meta-llama/llama-4-scout-17b-16e-instruct
