#Agent Settings
CONVERSATION_PROVIDER_URL=https\://openrouter.ai/api/v1
CONVERSATION_MODEL_ID=z-ai/glm-4.5-air\:free
CONVERSATION_PROVIDER_API_KEY=
MEMORY_PROVIDER_URL=https\://openrouter.ai/api/v1
MEMORY_MODEL_ID=tngtech/deepseek-r1t2-chimera\:free
MEMORY_PROVIDER_API_KEY=
