package io.github.jjdelcerro.noema.lib;

import java.util.Map;

/**
 * Public contract for an isolated, task-oriented worker subagent.
 * Extends Agent for polymorphism and AutoCloseable for deterministic resource disposal.
 */
public interface Subagent extends Agent, AutoCloseable {

    enum Status {
        CREATED,
        RUNNING,
        FINISHED,
        FAILED,
        CLOSED
    }

    /**
     * Returns the unique numeric identifier of this subagent instance.
     */
    int getId();

    /**
     * Returns the declarative recipe definition governing this subagent.
     */
    SubagentDefinition getDefinition();

    /**
     * Executes the subagent recipe synchronously in the current thread.
     *
     * @param params Key-value map used to resolve placeholders in prompts.
     * @return The final textual response produced by the subagent.
     */
    String run(Map<String, ?> params);

    /**
     * Launches the subagent execution asynchronously in a background thread.
     * Registers itself in AgentManager, notifies the originating subchannel upon
     * completion, and unregisters when finished.
     *
     * @param params Key-value map used to resolve placeholders in prompts.
     * @return The unique numeric ID of the launched subagent.
     */
    int launch(Map<String, ?> params);

    /**
     * Returns the current lifecycle status of the subagent.
     */
    Status getStatus();

    /**
     * Returns the last textual response generated by the model during execution.
     */
    String getLastResponse();

    /**
     * Returns the exception that caused the failure, or null if execution succeeded.
     */
    Throwable getLastError();

    /**
     * Stops internal services, closes database connections, and deletes the temporary workspace.
     */
    @Override
    void close();
}

